FROM jenkins/jenkins


USER root
RUN usermod -u 1000 jenkins && \
    groupmod -g 1000 jenkins


RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y python3 python3-pip curl git less && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install ansible --upgrade --break-system-packages

# إصلاح الصلاحيات
RUN mkdir -p /var/jenkins_home && \
    chown -R jenkins:jenkins /var/jenkins_home

USER jenkins
